<option value="">Select</option>
<option value="Andhra Pradesh">@lang("Andhra Pradesh")</option>
<option value="Arunachal Pradesh">@lang("Arunachal Pradesh")</option>
<option value="Assam">@lang("Assam")</option>
<option value="Bihar">@lang("Bihar")</option>
<option value="Chhattisgarh">@lang("Chhattisgarh")</option>
<option value="Goa">@lang("Goa")</option>
<option value="Gujarat">@lang("Gujarat")</option>
<option value="Haryana">@lang("Haryana")</option>
<option value="Himachal Pradesh">@lang("Himachal Pradesh")</option>
<option value="Jammu and Kashmir">@lang("Jammu and Kashmir")</option>
<option value="Jharkhand">@lang("Jharkhand")</option>
<option value="Karnataka">@lang("Karnataka")</option>
<option value="Kerala">@lang("Kerala")</option>
<option value="Madhya Pradesh">@lang("Madhya Pradesh")</option>
<option value="Maharashtra">@lang("Maharashtra")</option>
<option value="Manipur">@lang("Manipur")</option>
<option value="Meghalaya">@lang("Meghalaya")</option>
<option value="Mizoram">@lang("Mizoram")</option>
<option value="Nagaland">@lang("Nagaland")</option>
<option value="Orissa">@lang("Orissa")</option>
<option value="Punjab">@lang("Punjab")</option>
<option value="Rajasthan">@lang("Rajasthan")</option>
<option value="Sikkim">@lang("Sikkim")</option>
<option value="Tamil Nadu">@lang("Tamil Nadu")</option>
<option value="Tripura">@lang("Tripura")</option>
<option value="Uttarakhand">@lang("Uttarakhand")</option>
<option value="Uttar Pradesh">@lang("Uttar Pradesh")</option>
<option value="West Bengal">@lang("West Bengal")</option>
<option value="Tamil Nadu">@lang("Tamil Nadu")</option>
<option value="Tripura">@lang("Tripura")</option>
<option value="Andaman and Nicobar Islands">@lang("Andaman and Nicobar Islands")</option>
<option value="Chandigarh">@lang("Chandigarh")</option>
<option value="Dadra and Nagar Haveli">@lang("Dadra and Nagar Haveli")</option>
<option value="Daman and Diu">@lang("Daman and Diu")</option>
<option value="Delhi">@lang("Delhi")</option>
<option value="Lakshadweep">@lang("Lakshadweep")</option>
<option value="Pondicherry">@lang("Pondicherry")</option>
